// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzPzTYazYUc5Wc0C5T8AZJ2fyOsQy-sQ',
    appId: '1:39987383091:web:3961f4eba1ab9523fbcc46',
    messagingSenderId: '39987383091',
    projectId: 'studio-1794461068-2d7dd',
    authDomain: 'studio-1794461068-2d7dd.firebaseapp.com',
    storageBucket: 'studio-1794461068-2d7dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1yEjYDpqCUwwEgezU3V1qw0D3gMmRDlQ',
    appId: '1:39987383091:android:4f2d0ffd8679135ffbcc46',
    messagingSenderId: '39987383091',
    projectId: 'studio-1794461068-2d7dd',
    storageBucket: 'studio-1794461068-2d7dd.firebasestorage.app',
  );

  // From ios/Runner/GoogleService-Info.plist; the CLI's iOS step needs
  // the xcodeproj Ruby gem, which this Mac's system Ruby lacks.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTTXtObnSvPibMpY5dKZy6k3n39bKuQA',
    appId: '1:39987383091:ios:68be652700983e29fbcc46',
    messagingSenderId: '39987383091',
    projectId: 'studio-1794461068-2d7dd',
    storageBucket: 'studio-1794461068-2d7dd.firebasestorage.app',
    iosBundleId: 'com.kaylo.partner',
  );
}
